import React from "react";
import Faq from "react-faq-component";

const data = {
  title: <p> FAQs </p>,
  rows: [
    {
      title: <p> HOW TRANSACTIONS CAN BE PERFORMED?</p>,
      content: (
        <p>
          Transactions in Povo can be made with a variety of digital funds. This
          include your crypto currencies, NFT tokens. You can purchase Povo
          tokens with fiat currency or swap with other crypto assets, as well.
        </p>
      ),
    },
    {
      title: <p>HOW CROSS CHAIN FUNCTIONALITIES WORK?</p>,
      content: (
        <p>
          It works by allowing exchange of different cryptocurrencies between
          different pairs. It basically works as a currency exchange to
          facilitate your transfer/swap of crypto assets.
        </p>
      ),
    },
    {
      title: <p>WHAT IS MULTIVERSE USE CASE IN BLOCKCHAIN GAME?</p>,
      content: (
        <p>
          Multiverses can be used in gaming as an advanced feature to enter in
          parallel universes to explore new area and levels within the game.
        </p>
      ),
    },
    {
      title: <p>IS THERE ANY LIMIT IN FUND WITHDRAWAL?</p>,
      content: (
        <p>
          Generally, there is not limit implied on withdrawal of your funds with
          Povo. You can withdrawal at any time and for any amount.
        </p>
      ),
    },
    {
      title: <p>I HAVE RECEIVED POVO CARD, WHAT TO DO NEXT?</p>,
      content: (
        <p>
          Now that you have your Povo card, you can unlock NFT’s exclusive
          farms. You can mint NFTs or liquidate your Povo cards at any time or
          swap them with other crypto assets.
        </p>
      ),
    },
    {
      title: <p>What do I need to do to join Povo testnet?</p>,
      content: (
        <ul>
          <li>Compatible Wallet</li>
          <li>Povo extension </li>
          <li>Required some BNB/Eth or TEX for tranction</li>
        </ul>
      ),
    },
    {
      title: <p>NFTs copyrights</p>,
      content: (
        <ul>
          <li>We have partnered with various artists</li>
          <li>
            We are digitalizing gaming assets like hammer, shovel, boxes etc,
            with unique characteristics
          </li>
          <li>
            These assets are generated by users and licensed under POVO NFTs
          </li>
          <li>User can sell these NFTs (gaming assets) in market place.</li>
        </ul>
      ),
    },
  ],
};

const styles = {
  bgColor: "transparenet",
  titleTextColor: "white",
  rowTitleColor: "white",
  rowContentColor: "white",
  arrowColor: "white",
};

const config = {
  // animate: true,
  // arrowIcon: "V",
  // tabFocus: true
};

function Faqs() {
  return (
    <div className="backpic-table  p-5">
      <div className="container spotbox  ">
        <Faq data={data} styles={styles} config={config} />
      </div>
    </div>
  );
}

export default Faqs;
